spring.application.name=rookiesvnclient-api



spring.datasource.url=jdbc:mariadb://localhost:3306/rookiesvnclient
spring.datasource.username=root
spring.datasource.password=hjw12
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



svn.url=${SVN_SERVER_A_URL}
svn.username=hjw12
svn.password=gjwlsdnr@123



